### ISSUE TITLE
一些关于您博文的问题

### ISSUE THREAD

**Issue by Ray-Eldath** [wwulfric/wwulfric.github.io#1]
- 您在[Jekyll 博客的一些优化插件与配置](http://wulfric.me/2014/09/jekyll-plugs/)中提到了Jekyll的公示渲染。但kramdown的MathJax不能渲染以`$`标记的行内公式，而且对独行公示的渲染支持也不标准，请问这该如何解决？

以及您博客的livere评论好像无法正常登录？每次登录显示成功但根本就没登进去啊=-=

**Comment by wwulfric** [comment]
@Ray-Eldath 不好意思没看到评论，我没有用 kramdown 的渲染，而是将这个工作留给了 mathjax。https://raw.githubusercontent.com/wwulfric/articles/master/2014-09-01-design-of-sms-verification.md

```
---
title: 短信验证的设计
date: 2014-09-01 01:05
categories: [技术]
tags: [otp, 二次验证]
math: true
---
```

math true 的时候我会引入 mathjax js 文件，否则不引入。livere 我自己还没试过，我去试试看。谢谢提醒（可能太迟了😅）
